// Code generated by "stringer -type=Op"; DO NOT EDIT.

package ops

import "fmt"

const _Op_name = "OpOrOpAndOpLtOpBitOrOpBitXorOpBitAndOpShiftLOpConcatOpAddOpMulOpNegOpPowOpLeqOpShiftROpSubOpDivOpNotOpGtOpFloorDivOpLenOpGeqOpModOpBitNotOpEqOpIdOpNeq"

var _Op_map = map[Op]string{
	0:    _Op_name[0:4],
	1:    _Op_name[4:9],
	2:    _Op_name[9:13],
	3:    _Op_name[13:20],
	4:    _Op_name[20:28],
	5:    _Op_name[28:36],
	6:    _Op_name[36:44],
	7:    _Op_name[44:52],
	8:    _Op_name[52:57],
	9:    _Op_name[57:62],
	10:   _Op_name[62:67],
	11:   _Op_name[67:72],
	258:  _Op_name[72:77],
	262:  _Op_name[77:85],
	264:  _Op_name[85:90],
	265:  _Op_name[90:95],
	266:  _Op_name[95:100],
	514:  _Op_name[100:104],
	521:  _Op_name[104:114],
	522:  _Op_name[114:119],
	770:  _Op_name[119:124],
	777:  _Op_name[124:129],
	778:  _Op_name[129:137],
	1026: _Op_name[137:141],
	1034: _Op_name[141:145],
	1282: _Op_name[145:150],
}

func (i Op) String() string {
	if str, ok := _Op_map[i]; ok {
		return str
	}
	return fmt.Sprintf("Op(%d)", i)
}
